### ISSUE TITLE
issues versus questions

### ISSUE THREAD

**Issue by Mission5melissa** [Mission5/steamography#29]
hey tim - do you want us to pose questions in the issues area or just put stuff in here that needs to be fixed?  Just wondering so we don't confuse you.

Is there a better place for stuff we want to ask about or discuss as possibilities?
 thanks!

**Comment by timmhayes** [comment]
If they are questions about the site, then this is a great place to have a conversation - just make sure to clarify that you are asking for information rather than asking for a change. You should also assign the issue to the people you want to contribute. And please mark the issue as closed when the conversation is complete. I will mark the issues _I_ close as complete, but these kinds of issues are harder to close... so it is more up to the person asking the question to do that.

**Comment by Mission5melissa** [comment]
Thanks Tim. That's what we needed to know. 

Melissa

**Comment by timmhayes** [comment]
Feel free to follow my advice then and close the issue :-)

**Comment by Mission5melissa** [comment]
haha
