### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by timmhayes** [Mission5/steamography#31]
Does Leland have an existing Google Analytics account? If not, he needs one. Or I can use mine... but the site should have GA enabled from day 1.

**Comment by StanWebb** [comment]
We can set-up a GA account with Leland. If you can set-up the site and 
zip it that would be great. I am not that great with GitHub yet. I will 
get with Leland about the sub domain and get the ball rolling there. 
Stan

On Wed, 05 Apr 2017 19:56:03 -0700, Tim Hayes  wrote:

       Assigned #31 to @StanWebb. 
—
You are receiving this because you were mentioned. 
Reply to this email directly, view it on GitHub, or mute the thread. 

   *

**Comment by timmhayes** [comment]
OK Stan. I just e-mailed a zip with the site files in it. Please let me know if that works for you.

**Comment by Mission5melissa** [comment]
Leland said in an email that he does have GA - so he may have an account already.  Maybe a short call to talk about the tech side would be a good idea.  Are either of you available Wednesday afternoon/evening?

**Comment by StanWebb** [comment]
I will be around. Stan

On Tue, 11 Apr 2017 07:34:59 -0700, Mission5melissa  wrote:

       Leland said in an email that he does have GA - so he may have an 
account already. Maybe a short call to talk about the tech side would 
be a good idea. Are either of you available Wednesday afternoon/evening?
—
You are receiving this because you were mentioned. 
Reply to this email directly, view it on GitHub, or mute the thread. 

   *

**Comment by timmhayes** [comment]
I should be available after 7 pm or so.  Did Leland provide you with a GA tracking ID?

**Comment by Mission5melissa** [comment]
Possible GA number for my lelandmelvin@gmail.com account UA44101510-1

**Comment by StanWebb** [comment]
He will be back in town sometime today. I left a message for him to 
call me. Stan

On Tue, 11 Apr 2017 19:33:31 -0700, Tim Hayes  wrote:

       I should be available after 7 pm or so. Did Leland provide you 
with a GA tracking ID?
—
You are receiving this because you were mentioned. 
Reply to this email directly, view it on GitHub, or mute the thread. 

   *

**Comment by Mission5melissa** [comment]
Possible GA number for lelandmelvin@gmail.com account UA44101510-1

**Comment by timmhayes** [comment]
I haven't added this yet, but I wanted to confirm... will this be running from the lelandmelvin.com domain?

**Comment by Mission5melissa** [comment]
you mean the site overall? - as far as I know - yes - but Stan should confirm - I think it's a subdomain actually...Sorry I am not much help

**Comment by timmhayes** [comment]
This should be updated on commit f3cd6a242804ed990b380693e27aade674612bd7, but @StanWebb will need to add a new build to Leland's site to make sure everything works. It works great from BlueMix on my account.

**Comment by StanWebb** [comment]
Can you give me the complete site like last time and I will load 
everything up to test. Stan

On Wed, 17 May 2017 19:48:19 -0700, Tim Hayes  wrote:

       This should be updated on commit f3cd6a2, but @StanWebb will 
need to add a new build to Leland's site to make sure everything works. 
It works great from BlueMix on my account. 
—
You are receiving this because you were mentioned. 
Reply to this email directly, view it on GitHub, or mute the thread. 

   *

**Comment by timmhayes** [comment]
I just re-built the site and added a zip file to the shared folder on Google Drive for you.

**Comment by Mission5melissa** [comment]
Thanks Tim - so we have a build to upload and test?!  Yeah! That is great!

Stan - if you can get it up today and send out the link we have several folks ready to begin testing to make sure we are all good.  

We will start feeding comments into Github for fixes tonight and tomorrow - (unless there is a better way)  so we can address errors and have a final push on Sunday.  If we can, I'd like to have everything there and locked no later than Monday afternoon so Leland has time to look at it before his interview on CBS this morning on Tuesday the 23rd.

Does that sound feasible?  I"ll leave the minute details to ya'll but let me know when its up and I'll start with the iPad and alert others.  Monica and I will be testing on her laptop tomorrow, etc.

Thanks everybody!

Melissa
